repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.12.10
  hooks:
    - id: ruff-check
      args: [ --fix]
    - id: ruff-format
- repo: https://github.com/psf/black
  rev: 24.4.2
  hooks:
    - id: black
- repo: https://github.com/pycqa/isort
  rev: 6.0.1
  hooks:
    - id: isort
      name: isort (python)
      args: [--profile, black]
- repo: https://github.com/codespell-project/codespell
  rev: v2.4.1 # Use the latest stable version of codespell
  hooks:
    - id: codespell
- repo: https://github.com/RobertCraigie/pyright-python
  rev: v1.1.405
  hooks:
  - id: pyright
